# Generated by Django 3.2 on 2021-12-11 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombrefeefw', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerias.galeria')),
            ],
        ),
    ]
