# Generated by Django 3.2 on 2021-12-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadro',
            name='nombrefeefw',
        ),
    ]
