# Generated by Django 3.2 on 2021-12-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0002_remove_cuadro_nombrefeefw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadro',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cuadro',
            name='galeria',
        ),
        migrations.RemoveField(
            model_name='cuadro',
            name='imagen',
        ),
    ]
