# Generated by Django 3.2 on 2021-12-11 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0003_auto_20211211_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
