# Generated by Django 3.2 on 2021-12-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0004_cuadro_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='galeria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='galerias.galeria'),
            preserve_default=False,
        ),
    ]
