# Generated by Django 3.2 on 2021-12-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0005_cuadro_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='imagen',
            field=models.ImageField(default=None, upload_to='cuadros/'),
            preserve_default=False,
        ),
    ]
