# Generated by Django 3.2 on 2021-12-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0006_cuadro_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadro',
            name='imagen',
        ),
    ]
